import { PORTLAND } from "./cities";

export const STATE_MAP = {
  alabama: { supported: false },
  alaska: { supported: false },
  arizona: { supported: false },
  arkansas: { supported: false },
  california: { supported: false },
  colorado: { supported: false },
  connecticut: { supported: false },
  delaware: { supported: false },
  florida: { supported: false },
  georgia: { supported: false },
  hawaii: { supported: false },
  idaho: { supported: false },
  illinois: { supported: false },
  indiana: { supported: false },
  iowa: { supported: false },
  kansas: { supported: false },
  kentucky: { supported: false },
  louisiana: { supported: false },
  maine: { supported: false },
  maryland: { supported: false },
  massachusetts: { supported: false },
  michigan: { supported: false },
  minnesota: { supported: false },
  mississippi: { supported: false },
  missouri: { supported: false },
  montana: { supported: false },
  nebraska: { supported: false },
  nevada: { supported: false },
  new_hampshire: { supported: false },
  new_jersey: { supported: false },
  new_mexico: { supported: false },
  new_york: { supported: false },
  north_carolina: { supported: false },
  north_dakota: { supported: false },
  ohio: { supported: false },
  oklahoma: { supported: false },
  oregon: { supported: true, cities: [{ name: PORTLAND, supported: true }] },
  pennsylvania: { supported: false },
  rhode_island: { supported: false },
  south_carolina: { supported: false },
  south_dakota: { supported: false },
  tennessee: { supported: false },
  texas: { supported: false },
  utah: { supported: false },
  vermont: { supported: false },
  virginia: { supported: false },
  washington: { supported: true },
  west_virginia: { supported: false },
  wisconsin: { supported: false },
  wyoming: { supported: false },
};

export type State = keyof typeof STATE_MAP;
