name: Lint and Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-build:
    name: Lint and build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/node-and-dependencies
    
      - uses: ./.github/actions/cache-nextjs
      
      # Next.js automatically lints when it builds, 
      - name: Build
        run: npm run build
        
